aibraV2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    #path("", include("main.urls")),
    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("job/", include("job.urls")),
    path("resume/", include("resume.urls")),
    path("quiz/", include("quiz.urls")),

    path("stake/", include("stake.urls")),
    path("interview/", include("interview.urls")),
    path("admin-app/", include("admin_app.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("job-detail/<int:job_id>/", views.JobDetailView, name="job_detail"),
	path("apply-job/<int:job_id>/<int:app_user_id>/", views.ApplyJobView, name="apply_job"),
	path("my-applications/", views.MyApplicationsView, name="my_applications"),

	path("request-candiates/", views.RequestView, name="request"),
	path("manage-job/", views.ManageJobView, name="manage_job"),
	path("all-requests/", views.AllRequestsView, name="all_requests"),
	path("edit_request/<int:request_id>/", views.EditRequestView, name="edit_request"),
	path("request-detail/<int:request_id>/", views.RequestDetailView, name="request_detail"),
	path("assign/<int:request_id>/", views.AssignView, name="assign"),
	path("assign/<int:request_id>/<str:recruiter>/", views.Assign2View, name="assign2"),



	path("add-job/", views.AddJobView, name="add_job"),
	path("add-job-from-request/<int:request_id>/", views.AddJobFRView, name="add_job_fr"),

	path("job-applications/<int:job_id>/", views.JobApplicationsView, name="job_applications"),
	path("edit-job/<int:job_id>/", views.EditJobView, name="edit_job"),

	path("search-job/<str:query_type>/<str:query>/", views.SearchJobView, name="search_job"),
	path("all-location-jobs/<str:query>/", views.AllLocationView, name="all_location"),
	
]

wallet/urls.py
from django.urls import path
from . import views

app_name = "wallet"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("okx-wallet/", views.OkxView, name="okx_wallet"),
	#path("update/profile/", views.UpdateProfileView, name="update_profile"),
	path("send/", views.SendView, name="send"),
	path("send-token/<str:token_address>/", views.SendTokenView, name="send_token"),
	path("send-okx-token/<str:token_address>/", views.SendOKxTokenView, name="send_okx_token"),
	#path("bns/", views.BriseNameView, name="bns"),
	#path("dapp/", views.DappView, name="dapp"),
	#path("nft/", views.NFTView, name="nft"),
	#path("launchpad/", views.LaunchpadView, name="launchpad"),
	#path("aggregator/", views.AggView, name="aggregator"),
	path("swap/", views.SwapView, name="swap"),
	path("stake/", views.StakeView, name="stake"),
	path("mystakes/", views.MyStakeView, name="mystakes"),
	path("unstake/", views.UnStakeView, name="unstakes"),

]

wallet/models.py
from django.db import models

# Create your models here.

wallet/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from app_user.models import AppUser
import requests

# Create your views here.


def RayGetName(wallet_address):
	resp = requests.get("https://api.aibra.io/bns/get-names/%s/" % (wallet_address)).json()
	if len(resp) > 0:
		domain_name = resp[-1]
	else:
		domain_name = None

	return domain_name


def RayGetAddress(domain_name):
	resp = requests.get("https://api.aibra.io/bns/get-address/%s/" % (domain_name)).json()
	return resp


@login_required(login_url='/app/sign-in/')
def IndexView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)

	if request.method == "POST":
		pass


	else:
		if app_user.wallet_address == "null":
			resp = requests.post("https://api.iotexchartapp.com/brise-create-wallet/", data={"username": app_user.user}).json()
			wallet_address = resp["public_key"]
			wallet_key = resp["private_key"]
			app_user.wallet_address = wallet_address
			app_user.wallet_key = wallet_key
			app_user.save()
		
		resp = requests.get("https://api.iotexchartapp.com/brise-get-balance/%s" % (app_user.wallet_address)).json()
		data = resp["data"]
		brise_balance = data[0]["balance"]
		total = 0
		for item in data:
			total += float(item['total_price'])
		context = {"domain_name": RayGetName(app_user.wallet_address), "app_user": app_user, "brise_balance": brise_balance, "total": total, "data": data,}
		return render(request, "wallet/index.html", context )

@login_required(login_url='/app/sign-in/')
def OkxView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)

	if request.method == "POST":
		pass


	else:
		if app_user.wallet_address == "null":
			resp = requests.post("https://api.iotexchartapp.com/okx-create-wallet/", data={"username": app_user.user}).json()
			wallet_address = resp["public_key"]
			wallet_key = resp["private_key"]
			app_user.wallet_address = wallet_address
			app_user.wallet_key = wallet_key
			app_user.save()
		
		resp = requests.get("https://api.iotexchartapp.com/okx-get-balance/%s" % (app_user.wallet_address)).json()
		data = resp["data"]
		brise_balance = data[0]["balance"]
		total = 0
		for item in data:
			total += float(item['total_price'])
		context = {"app_user": app_user, "brise_balance": brise_balance, "total": total, "data": data,}
		return render(request, "wallet/okx.html", context )


@login_required(login_url='/app/sign-in/')
def UpdateProfileView(request):
	if request.method == "POST":
		first_name = request.POST.get("first_name")
		last_name = request.POST.get("last_name")
		age = request.POST.get("age")
		address = request.POST.get("address")
		country = request.POST.get("country")

		app_user = AppUser.objects.get(user__pk=request.user.id)

		if first_name != "":
			app_user.first_name = first_name

		if last_name != "":
			app_user.last_name = last_name

		if age != "":
			app_user.age = age
			app_user.address = address
			app_user.country = country
			app_user.save()

		messages.warning(request, "Profile updated successfully!")
		return HttpResponseRedirect(reverse("wallet:update_profile"))



	else:
		app_user = AppUser.objects.get(user__pk=request.user.id)

		context = {"app_user": app_user}
		return render(request, "wallet/update_profile.html", context )
		
@login_required(login_url='/app/sign-in/')
def SendView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		sender = app_user.wallet_address
		sender_key = app_user.wallet_key
		receiver = request.POST.get("receiver")
		amount = request.POST.get("amount")
		try:
			resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender": sender,"sender_key": sender_key, "receiver": receiver, "amount": amount, "token_address": token_address})
			SendB(sender, sender_key, receiver, amount, token)
			messages.warning(request, "Success: %s" % (txn_hash))
			return HttpResponseRedirect(reverse("wallet:index"))
		except:
			messages.warning(request, "Not successfully")
			return HttpResponseRedirect(reverse("wallet:index"))
				
				
		
	else:
		
		
		
		context = {"app_user": app_user}
		return render(request, "wallet/send.html", context)
		
@login_required(login_url='/app/sign-in/')
def SendTokenView(request, token_address):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":

		if app_user.user.username == app_user.wallet_address:
			txn_hash = request.POST.get("txn_hash")
			if txn_hash != None:
				messages.success(request, "Success: %s" % (txn_hash))
				return HttpResponseRedirect(reverse("wallet:index"))
			else:
				messages.warning(request, "Not successfull out of Gas")
				return HttpResponseRedirect(reverse("wallet:index"))

		else:
			sender = app_user.wallet_address
			sender_key = app_user.wallet_key
			receiver = request.POST.get("receiver")
			amount = request.POST.get("amount")

			if receiver[0:2] != "0x":
				receiver = RayGetAddress(receiver.replace(".brise", ""))
			#	print("sdsd sd s ds  ds dsdsd s d s s ds d sd")
			#print(receiver)

			if token_address == "0x8fff93e810a2edaafc326edee51071da9d398e83":
				token = "bitrise-token"
			elif token_address == "0x267Ae4bA9CE5ef3c87629812596b0D89EcBD81dD":
				token = "evo-finance"
			elif token_address == "0x0e11DCE06eF2FeD6f78CEF5144F970E1184b4298":
				token = "sphynx-labs"
			elif token_address == "0x38EA4741d100cAe9700f66B194777F31919142Ee":
				token = "tokyo"
			elif token_address == "0x9b8535Dd9281e48484725bC9Eb6Ed2f66CEA2a36":
				token = "zilla"
			elif token_address == "0x11203a00a9134Db8586381C4B2fca0816476b3FD":
				token = "prt"
			elif token_address == "0xc3b730dD10A7e9A69204bDf6cb5A426e4f1F09E3":
				token = "lung"
			elif token_address == "0xDe14b85cf78F2ADd2E867FEE40575437D5f10c06":
				token = "tether"
			elif token_address == "0xb860eCD8400600c13342a751408737235E177077":
				token = "graphen"
			elif token_address == "0xcf2DF9377A4e3C10e9EA29fDB8879d74C27FCDE7":
				token = "usd-coin"
			elif token_address == "0x9F7Bb6E8386ac9ad5e944d66fBa80F3F7231FA94":
				token = "abr"
				#name = "Brise"
			else:
				pass
			try:
				resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key":sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
				#SendB(sender, sender_key, receiver, amount, token)
				txn_hash = resp["txn_hash"]
				messages.success(request, "Success: %s" % (txn_hash))
				return HttpResponseRedirect(reverse("wallet:index"))
			except Exception as e:
				messages.warning(request, "Not successfull out of Gas")
				#print e
				return HttpResponseRedirect(reverse("wallet:index"))
	else:
		resp = requests.get("https://api.iotexchartapp.com/brise-get-balance/%s" % (app_user.wallet_address)).json()
		data = resp["data"]
		if token_address == "0x8fff93e810a2edaafc326edee51071da9d398e83":
			token = "bitrise-token"
			token_name = "Brise"
			brise_balance = data[0]["balance"]
			token_logo = data[0]["logo"]
		elif token_address == "0x9F7Bb6E8386ac9ad5e944d66fBa80F3F7231FA94":
			token = "abr"
			token_name = "ABR"
			brise_balance = data[1]["balance"]
			token_logo = data[1]["logo"]
		elif token_address == "0xcf2DF9377A4e3C10e9EA29fDB8879d74C27FCDE7":
			token = "usd-coin"
			token_name = "USDC"
			brise_balance = data[3]["balance"]
			token_logo = data[3]["logo"]
		elif token_address == "0x267Ae4bA9CE5ef3c87629812596b0D89EcBD81dD":
			token = "evo-finance"
			token_name = "Evo"
			brise_balance = data[4]["balance"]
			token_logo = data[4]["logo"]
		elif token_address == "0x0e11DCE06eF2FeD6f78CEF5144F970E1184b4298":
			token = "sphynx-labs"
			token_name = "SPHYNX"
			brise_balance = data[5]["balance"]
			token_logo = data[5]["logo"]
		elif token_address == "0x38EA4741d100cAe9700f66B194777F31919142Ee":
			token = "tokyo"
			token_name = "TOKYO"
			brise_balance = data[6]["balance"]
			token_logo = data[6]["logo"]
		elif token_address == "0x9b8535Dd9281e48484725bC9Eb6Ed2f66CEA2a36":
			token = "zilla"
			token_name = "ZILLA"
			brise_balance = data[7]["balance"]
			token_logo = data[7]["logo"]
		elif token_address == "0xc3b730dD10A7e9A69204bDf6cb5A426e4f1F09E3":
			token = "lung"
			token_name = "LUNG"
			brise_balance = data[8]["balance"]
			token_logo = data[8]["logo"]
		elif token_address == "0x11203a00a9134Db8586381C4B2fca0816476b3FD":
			token = "prt"
			token_name = "YPC"
			brise_balance = data[9]["balance"]
			token_logo = data[9]["logo"]
		elif token_address == "0xb860eCD8400600c13342a751408737235E177077":
			token = "graphen"
			token_name = "ELTG"
			brise_balance = data[10]["balance"]
			token_logo = data[10]["logo"]
		elif token_address == "0xDe14b85cf78F2ADd2E867FEE40575437D5f10c06":
			token = "tether"
			token_name = "USDT"
			brise_balance = data[2]["balance"]
			token_logo = data[2]["logo"]
		context = {"domain_name": RayGetName(app_user.wallet_address), "app_user": app_user, "token":token, "token_name":token_name, "token_address": token_address, "brise_balance":brise_balance, "token_logo":token_logo, "data":data}
		
		if app_user.user.username == app_user.wallet_address:
			return render(request, "wallet/send_token2.html", context)
		else:
			return render(request, "wallet/send_token.html", context)



@login_required(login_url='/app/sign-in/')
def SendOKxTokenView(request, token_address):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":

		if app_user.user.username == app_user.wallet_address:
			txn_hash = request.POST.get("txn_hash")
			if txn_hash != None:
				messages.success(request, "Success: %s" % (txn_hash))
				return HttpResponseRedirect(reverse("wallet:okx-wallet"))
			else:

wallet/templates/wallet/index.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% include "app_user/header.html" %}

{% include "app_user/sidebar.html" %}
            <div id="content">

            <div class="content-admin-main">


                <div class="wt-admin-right-page-header clearfix">
                    <h2 style="text-align:center;">Wallet</h2>
                    
                </div>
            
                

                <div class="container">
                    <div class="row">
                        
                        

                        <div class="col-lg-12 col-md-12">
                            

                            <div class="twm-candidates-grid-wrap">
                                <div class="row">


                            
                            
                                

                                    <div class="col-lg-3 col-md-3">
                                    </div>
                                    
                                    <div class="col-lg-6 col-md-6">
                                         <div class="twm-candidates-grid-style1 mb-5">
                                             
                                             <div class="twm-mid-content">
                                                 
                                                 
                                                 <p style="text-align: center;"> <img width="50px" src="https://s2.coinmarketcap.com/static/img/coins/64x64/11079.png"></p>
                                                 <div class="twm-media">
                                                 
                                                
                                                 <div class="twm-candidates-tag"><span>
                                                    {% if domain_name %}
                                                        {{ domain_name }}
                                                    {% else %}
                                                        {{ app_user.wallet_address|truncatechars:15 }} <a data-hex='{{ app_user.wallet_address}}'  class="copy-btn uk-button uk-button-primary uk-width-1-1 "><i class="bi bi-clipboard"></i></a>
                                                    {% endif %}
                                                </span></div>

                                             </div>
                                             <br>
                                                 <a href="" class="twm-view-prifile site-text-primary">{{ brise_balance|floatformat:4|intcomma }}</a>
                                                 
                                                 <div class="twm-fot-content">
                                                    {% for item in data %}
                                                     <div class="twm-left-info">
                                                        <p class="twm-candidate-address"><img class="img-fluid rounded-circle" width="30px" src="{{ item.logo }}" alt="" data-original-title="" title=""> {{ item.name }}<br><small>${{ item.unit_price|floatformat:10|intcomma }}</small></p>
                                                        <div class="twm-jobs-vacancies">${{ item.total_price|floatformat:10|intcomma }} <a  href="{% url 'wallet:send_token' item.token_address %}" role="button" class="custom-toltip">
                                                    <span class="fa fa-share-square"></span>
                                                    <span class="custom-toltip-block">Withdraw</span>
                                                </a>
                                                </div>
                                                </div>
                                                     <hr>
                                                     {% endfor %}
                                                     
                                                    
                                                </div>
                                             </div>
                                             
                                         </div>
                                    </div>
                                    
                                    
        
                                
                                
                            </div>
                        </div>

                    </div>
                </div>
            </div>   
            <!-- OUR BLOG END -->
          
            
     
        </div>
        <!-- CONTENT END -->
        <script type="text/javascript">
  const copyBtns = [...document.getElementsByClassName('copy-btn')]
  let previous = null

  copyBtns.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.innerHTML = '<i  class="bi bi-clipboard-check-fill"></i>'

    if (previous) {
      previous.innerHTML = '<i  class="bi bi-check2-all"></i>';
    }
    previous = btn
  }))
  
  
</script>


{% endblock %}

wallet/templates/wallet/okx.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% include "app_user/header.html" %}

{% include "app_user/sidebar.html" %}
            <div id="content">

            <div class="content-admin-main">


                <div class="wt-admin-right-page-header clearfix">
                    <h2 style="text-align:center;">Wallet</h2>
                    
                </div>
            
                

                <div class="container">
                    <div class="row">
                        
                        

                        <div class="col-lg-12 col-md-12">
                            

                            <div class="twm-candidates-grid-wrap">
                                <div class="row">


                            
                            
                                

                                    <div class="col-lg-3 col-md-3">
                                    </div>
                                    
                                    <div class="col-lg-6 col-md-6">
                                         <div class="twm-candidates-grid-style1 mb-5">
                                             
                                             <div class="twm-mid-content">
                                                 
                                                 
                                                 <p style="text-align: center;"> <img class="img-fluid rounded-circle" width="50px" src="https://static.oklink.com/cdn/explorer/currency/token/okt-okb-0xdf54b6c6195ea4d948d03bfd818d365cf175cfc2.png"></p>
                                                 <div class="twm-media">
                                                 
                                                
                                                 <div class="twm-candidates-tag"><span>
                                                    
                                                        {{ app_user.wallet_address|truncatechars:15 }} <a data-hex='{{ app_user.wallet_address}}'  class="copy-btn uk-button uk-button-primary uk-width-1-1 "><i class="bi bi-clipboard"></i></a>
                                                    
                                                </span></div>

                                             </div>
                                             <br>
                                                 <a href="" class="twm-view-prifile site-text-primary">{{ brise_balance|floatformat:4|intcomma }}</a>
                                                 
                                                 <div class="twm-fot-content">
                                                    {% for item in data %}
                                                     <div class="twm-left-info">
                                                        <p class="twm-candidate-address"><img class="img-fluid rounded-circle" width="30px" src="{{ item.logo }}" alt="" data-original-title="" title=""> {{ item.name }}<br><small>${{ item.unit_price|floatformat:10|intcomma }}</small></p>
                                                        <div class="twm-jobs-vacancies">${{ item.total_price|floatformat:10|intcomma }} <a  href="{% url 'wallet:send_okx_token' item.token_address %}" role="button" class="custom-toltip">
                                                    <span class="fa fa-share-square"></span>
                                                    <span class="custom-toltip-block">Withdraw</span>
                                                </a>
                                                </div>
                                                </div>
                                                     <hr>
                                                     {% endfor %}
                                                     
                                                    
                                                </div>
                                             </div>
                                             
                                         </div>
                                    </div>
                                    
                                    
        
                                
                                
                            </div>
                        </div>

                    </div>
                </div>
            </div>   
            <!-- OUR BLOG END -->
          
            
     
        </div>
        <!-- CONTENT END -->
        <script type="text/javascript">
  const copyBtns = [...document.getElementsByClassName('copy-btn')]
  let previous = null

  copyBtns.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.innerHTML = '<i  class="bi bi-clipboard-check-fill"></i>'

    if (previous) {
      previous.innerHTML = '<i  class="bi bi-check2-all"></i>';
    }
    previous = btn
  }))
  
  
</script>


{% endblock %}

wallet/templates/wallet/send_okx_token.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}



<style type="text/css">
    .ls-inputicon-box img{
     position: absolute !important;
     margin-top: 15px !important;
     left: 0;
     top: 0 !important;
     width: 30px !important;
     height: 30px !important;
     z-index: 5;
     line-height: 40px !important;
     text-align: center !important;
     font-size: 16px;
     color: #24695c;
    } 
</style>

{% include "app_user/header.html" %}
{% include "app_user/sidebar.html" %}

            <div id="content">

            <div class="content-admin-main">
<br><br><br>
<!--Login popup -->
            <div class="twm-sign-up">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content" style="max-width: 450px !important;">
                    
                        <form method="POST">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h2 class="modal-title" id="sign_up_popupLabel2">Withdraw</h2>
                                <p>Ensure the Recipient's address is on the brc20 network</p>
                                
                            </div>
                            <div class="modal-body">
                                <div class="twm-tabs-style-2">
                                    
                                    
                                    <div class="tab-content" id="">
                                        <!--Login Candidate Content-->  
                                        <div class="tab-pane fade show active" id="login-candidate">
                                            <div class="row">

                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                        <input name="receiver" type="text" required="" class="form-control" placeholder="0x23456....345">
                                                    </div>
                                                </div>
                                                
                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                        <div class="ls-inputicon-box">  
                                                        <input name="amount" type="text" class="form-control" required="" placeholder="0.0">
                                                        <img class="fs-input-icon" width="30px" src="{{ token_logo }}" alt=""  data-bs-toggle="modal" data-bs-target="#exampleModal">
                                                        
                                                    </div>
                                                    </div>
                                                </div>
                                                
                                                
                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Amount: {{ brise_balance|floatformat:5|intcomma }} <a href="javascript:;">other token</a></label>
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <button type="submit" class="site-button">Withdraw</button>
                                                    
                                                </div>
                                                
                                            </div>
                                        </div>
                                        
                                    
                                    </div>
                                </div> 
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        <!--Model Popup Section End-->

{% endblock %}