aibraV2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    #path("", include("main.urls")),
    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("job/", include("job.urls")),
    path("resume/", include("resume.urls")),
    path("quiz/", include("quiz.urls")),

    path("stake/", include("stake.urls")),
    path("interview/", include("interview.urls")),
    path("admin-app/", include("admin_app.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("job-detail/<int:job_id>/", views.JobDetailView, name="job_detail"),
	path("apply-job/<int:job_id>/<int:app_user_id>/", views.ApplyJobView, name="apply_job"),
	path("my-applications/", views.MyApplicationsView, name="my_applications"),

	path("request-candiates/", views.RequestView, name="request"),
	path("manage-job/", views.ManageJobView, name="manage_job"),
	path("all-requests/", views.AllRequestsView, name="all_requests"),
	path("edit_request/<int:request_id>/", views.EditRequestView, name="edit_request"),
	path("request-detail/<int:request_id>/", views.RequestDetailView, name="request_detail"),
	path("assign/<int:request_id>/", views.AssignView, name="assign"),
	path("assign/<int:request_id>/<str:recruiter>/", views.Assign2View, name="assign2"),



	path("add-job/", views.AddJobView, name="add_job"),
	path("add-job-from-request/<int:request_id>/", views.AddJobFRView, name="add_job_fr"),

	path("job-applications/<int:job_id>/", views.JobApplicationsView, name="job_applications"),
	path("edit-job/<int:job_id>/", views.EditJobView, name="edit_job"),

	path("search-job/<str:query_type>/<str:query>/", views.SearchJobView, name="search_job"),
	path("all-location-jobs/<str:query>/", views.AllLocationView, name="all_location"),
	
]

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from interview.models import Interview
from quiz.models import Quiz, Result
from app_user.models import AppUser




class Answer(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	question_id = models.CharField(max_length=50, default="None")
	answer = models.CharField(max_length=50, default="None")
	
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.answer



class Application(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	answers = models.ManyToManyField(Answer, through="ApplicationAnswerConnector")

	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.app_user



class Job(models.Model):
	title = models.CharField(max_length=50, default="none")
	salary = models.CharField(max_length=30, default="none")
	category = models.CharField(max_length=30, default="none")
	description = models.TextField(default="none")
	company_logo = models.FileField(upload_to='account_files/profile_photos/', blank=True, default="default_files/default_face.jpg")
	job_type = models.CharField(max_length=20, default="none")
	experience = models.CharField(max_length=120, default="none")
	qualification = models.CharField(max_length=20, default="none", null=True)
	responsibility = models.TextField(default="none")
	skill_tag = models.CharField(max_length=2000, default="no skill required", null=True)
	requirement = models.TextField(default="none")
	contact_phone = models.CharField(max_length=20, default="none")
	contact_email = models.CharField(max_length=30, default="none")
	website = models.CharField(max_length=30, default="none")

	address = models.TextField(default="none")
	country = models.CharField(max_length=30, default="none")

	deadline = models.CharField(max_length=30, default="none")
	#deadline = models.DateTimeField(default=timezone.now)

	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	applications = models.ManyToManyField(Application, through="JobApplicationConnector")
	interviews = models.ManyToManyField(Interview, through="JobInterviewConnector")
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, null=True)
	results = models.ManyToManyField(Result, through="JobResultConnector")



	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title


class JobRequest(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
	recruiter = models.CharField(max_length=50, default="none")
	title = models.CharField(max_length=50, default="none")
	category = models.CharField(max_length=30, default="none")
	description = models.TextField(default="none")
	experience = models.CharField(max_length=120, default="none")
	salary = models.CharField(max_length=30, default="none")
	job_type = models.CharField(max_length=30, default="none")
	slots = models.CharField(max_length=20, default="none")
	deadline = models.CharField(max_length=30, default="none")
	website = models.CharField(max_length=30, default="none")
	address = models.CharField(max_length=30, default="none")

	job_id = models.CharField(max_length=30, default="none")
	
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title

class ApplicationAnswerConnector(models.Model):
	application = models.ForeignKey(Application, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)




class JobResultConnector(models.Model):
	job = models.ForeignKey(Job, on_delete=models.CASCADE)
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)




class JobApplicationConnector(models.Model):
	job = models.ForeignKey(Job, on_delete=models.CASCADE)
	application = models.ForeignKey(Application, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)



class JobInterviewConnector(models.Model):
	job = models.ForeignKey(Job, on_delete=models.CASCADE)
	interview = models.ForeignKey(Interview, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)

job/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.mail import send_mail

from datetime import datetime
import datetime as dt
import requests

from job.models import *
from app_user.models import AppUser
from app_user.views import RaySendMail
from django.contrib.auth.decorators import login_required
#from .forms import UserForm




@login_required(login_url='/sign-in/')
def IndexView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    jobs = Job.objects.all().order_by('-pub_date')

    job_types = set()
    countries = set()
    titles = set()
    categories = set()

    for item in jobs:
        job_types.add(item.job_type)
        countries.add(item.country)
        titles.add(item.title)
        categories.add(item.category)

    if request.method == "POST":
        location = request.POST.get("location")
        job_type = request.POST.get("job_type")
        category = request.POST.get("category")

        job = Job.objects.filter(job_type=job_type, country=location.replace("%20", " "), category=category)

        context = {"jobs": jobs,
        "job_types": job_types, "countries": countries,
        "titles": titles, "categories": categories}

        return render(request, "app_user/search_job.html", context )





    else:
        jobs = Job.objects.all().order_by('-pub_date')

        job_types = set()
        countries = set()
        titles = set()
        categories = set()

        for item in jobs:
            job_types.add(item.job_type)
            countries.add(item.country)
            titles.add(item.title)
            categories.add(item.category)



        context = {"app_user": app_user, "jobs": jobs,
        "job_types": job_types, "countries": countries,
        "titles": titles, "categories": categories}

        return render(request, "job/index.html", context )





def SearchJobView(request, query_type, query):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        pass


    else:

        jobs = Job.objects.all()

        job_types = set()
        countries = set()
        titles = set()
        categories = set()

        for item in jobs:
            job_types.add(item.job_type)
            countries.add(item.country)
            titles.add(item.title)
            categories.add(item.category)

        

        if query_type == "job_type":
            search_results = Job.objects.filter(job_type=query)

        elif query_type == "country":
            search_results = Job.objects.filter(country=query)

        elif query_type == "title":
            search_results = Job.objects.filter(title=query)

        elif query_type == "category":
            search_results = Job.objects.filter(category=query)

        else:
            pass


        context = {"app_user": app_user, "jobs": jobs, "search_results": search_results, 
        "job_types": job_types, "countries": countries,
        "titles": titles, "categories": categories}
        return render(request, "job/search_job.html", context )





def AllLocationView(request, query):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        pass


    else:

        jobs = Job.objects.all()

        job_types = set()
        countries = set()
        titles = set()
        categories = set()

        for item in jobs:
            job_types.add(item.job_type)
            countries.add(item.country)
            titles.add(item.title)
            categories.add(item.category)


        search_results = Job.objects.filter(country=query)


        context = {"app_user": app_user, "jobs": jobs, "search_results": search_results, 
        "job_types": job_types, "countries": countries,
        "titles": titles, "categories": categories}
        return render(request, "job/search_job.html", context )




#@login_required(login_url='/app/sign-in/')
def JobDetailView(request, job_id):
    try:
        app_user = AppUser.objects.get(user__pk=request.user.id)

    except:
        app_user = None

    if request.method == "POST":
        pass


    else:
        job = Job.objects.get(id=job_id)
        jobs = Job.objects.all()

        applied_status = False
        for item in job.applications.all():
            if item.app_user == app_user:
                applied_status = True

        job_types = set()
        countries = set()
        titles = set()
        categories = set()

        for item in jobs:
            job_types.add(item.job_type)
            countries.add(item.country)
            titles.add(item.title)
            categories.add(item.category)

        similar_jobs = Job.objects.filter(category=job.category)

        context = {"app_user": app_user, "job": job, "jobs": jobs, "applied_status": applied_status,
        "job_types": job_types, "countries": countries,
        "titles": titles, "categories": categories, "similar_jobs": similar_jobs}
        
        return render(request, "job/job_detail.html", context )


def AddJobFRView(request, request_id):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    job_request = JobRequest.objects.get(id=request_id)
    if request.method == "POST" and request.FILES['company_logo']:
        
        company_logo = request.FILES["company_logo"]
        
        title = request.POST.get("title")
        salary = request.POST.get("salary")
        category = request.POST.get("category")
        address = request.POST.get("address")
        country = request.POST.get("country")
        description = request.POST.get("description")
        job_type = request.POST.get("job_type")
        responsibility = request.POST.get("responsibility")
        requirement = request.POST.get("requirement")
        contact_email = request.POST.get("contact_email")
        contact_phone = request.POST.get("contact_phone")
        website = request.POST.get("website")
        deadline = request.POST.get("deadline")

        job = Job.objects.create(app_user=app_user, title=title, salary=salary, category=category, address=address, country=country, description=description, job_type=job_type,
            responsibility=responsibility, requirement=requirement, contact_email=contact_email, contact_phone=contact_phone,
            deadline=deadline, website=website, company_logo=company_logo)
        job.save()

        job_request.job_id = job.id
        job_request.save()
        #jr = JobRequestJobConnector(job_request=job_request, job=job)
        #jr.save()

        messages.warning(request, "Job Added!")
        return HttpResponseRedirect(reverse("job:manage_job"))


    else:
        jobs = Job.objects.filter(app_user=app_user).order_by("-pub_date")

        context = {"app_user": app_user, "jobs": jobs, "job_request": job_request}
        return render(request, "job/add_job_fr.html", context )


def ApplyJobView(request, job_id, app_user_id):
    app_user = AppUser.objects.get(id=app_user_id)
    job = Job.objects.get(id=job_id)

    application = Application.objects.create(app_user=app_user)
    application.save()

    ja = JobApplicationConnector(job=job, application=application)
    ja.save()
    
    to_email = job.contact_email
    code = job.id
    subject = "Aibra Jobs: New Application!"
    message = "You have a new application for one of your jobs"
    RaySendMail(request, subject, message, to_email, code=code)

    messages.warning(request, "Job Applied!")
    return HttpResponseRedirect(reverse("job:index"))



    if request.method == "POST":
        pass


    else:
        job = Job.objects.get(id=job_id)
        jobs = Job.objects.all()

        context = {"app_user": app_user, "job": job, "jobs": jobs}
        return render(request, "job/apply_job.html", context )



def MyApplicationsView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)

    if request.method == "POST":
        pass


    else:
        my_applications = []
        jobs = Job.objects.all()

        for item in jobs:
            for jtem in item.applications.all():
                if jtem.app_user == app_user:
                    my_applications.append(item)

        context = {"app_user": app_user, "my_applications": my_applications}
        return render(request, "job/my_applications.html", context )






def EditJobView(request, job_id):
    job = Job.objects.get(id=job_id)
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST" and request.FILES['company_logo']:
        company_logo = request.FILES["company_logo"]
        title = request.POST.get("title")
        salary = request.POST.get("salary")
        address = request.POST.get("address")
        category = request.POST.get("category")
        description = request.POST.get("description")
        responsibility = request.POST.get("responsibility")
        requirement = request.POST.get("requirement")
        contact_email = request.POST.get("contact_email")
        contact_phone = request.POST.get("contact_phone")
        deadline = request.POST.get("deadline")
        qualification = request.POST.get("qualification")
        experience = request.POST.get("experience")
        website = request.POST.get("website")
        job_type = request.POST.get("job_type")
        skill_tag = request.POST.get("skill_tag")
        country = request.POST.get("country")

        job.title = title
        job.company_logo = company_logo
        job.salary = salary
        job.address = address
        job.description = description

job/templates/job/index.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}



{% include "app_user/header.html" %}
{% include "app_user/sidebar.html" %}

<!--Page Content Holder -->
        <div id="content">

            <div class="content-admin-main">


                <div class="wt-admin-right-page-header clearfix">
                    <h2>Available Jobs</h2>
                    <div class="breadcrumbs"><a href="#">Dasboard</a><span>Change Password</span></div>
                </div>
                

                <div class="container">
                    <div class="row">
                        {% if messages %}
                                    {% for message in messages %}
                                        <div class="col-xl-12 col-lg-12 col-md-12 mb-5">
                                            <div class="twm-media">
                                                <div class="twm-candidates-tag" id="{{ loop.index }}" style="background-color: #e0eeff; padding: 10px; border-radius: 5px; text-align: center"><span style="color: #24695c; text-align: center">{{ message }}</span></div>
                                            </div>
                                        </div>
                                        <script>
                                            setTimeout(function() {
                                                var element = document.getElementById("{{ loop.index }}");
                                                element.parentNode.removeChild(element);
                                            }, 5000);
                                        </script>
                                    {% endfor %}
                                {% endif %}
                                
                        
                        <div class="col-lg-4 col-md-12 rightSidebar query">

                            <div class="side-bar">

                                <div class="sidebar-elements search-bx">
                                                                            
                                    <form method="post">
                                        
                                        <div class="form-group mb-4">
                                            <h4 class="section-head-small mb-4">Job Type</h4>
                                            <div class="tagcloud">
                                                {% for item in job_types %}
                                                    <a href="{% url 'job:search_job' 'job_type' item %}"><button class="btn btn-outline-primary mb-2" type="button"><i class="icofont icofont-star-shape"></i>{{ item }}</button></a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        
                                        

                                        <div class="form-group mb-4">
                                            <h4 class="section-head-small mb-4">By Country</h4>
                                            {% if countries %}
                                                <div class="tagcloud">
                                                    {% for item in countries %}
                                                        <a href="{% url 'job:search_job' 'country' item %}"><button class="btn btn-outline-primary mb-2" type="button"><i class="icofont icofont-star-shape"></i>{{ item }}</button></a>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                            <div class="tagcloud">
                                                Nothing yet!
                                            </div>
                                            {% endif %}

                                        </div>

                                        <div class="form-group mb-4">
                                            <h4 class="section-head-small mb-4">Category</h4>
                                            {% if categories %}
                                                {% for item in categories %}
                                                <a href="{% url 'job:search_job' 'category' item %}"><button class="btn btn-outline-primary mb-2" type="button"><i class="icofont icofont-star-shape"></i> {{ item }}</button></a>
                                                {% endfor %}
                                            {% else %}

                                            {% endif %}
                                        </div>

                                        

                                        
                                        
                                    </form>
                                    
                                </div>

                                

                                
                            </div>

                            

                        </div>

                        <div class="col-lg-8 col-md-12">
                            

                            <!--Filter Short By-->
                            <div class="  m-b30">
                                
                               <div class="twm-bnr-search-bar">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="row">


                                        <!--Title-->
                                        <div class="form-group col-xl-3 col-lg-6 col-md-6">
                                            <label>category</label>
                                            <select name="category" class="wt-search-bar-select selectpicker"  data-live-search="true" title="" id="j-Job_Title" data-bv-field="size">
                                                <option  value="all" selected>All Categories</option>
                                                {% for item in categories %}
                                                    <option value="{{ item }}">{{ item }}</option>
                                                {% endfor %} 
                                            </select>
                                        </div>

                                        <!--All Category-->
                                        <div class="form-group col-xl-3 col-lg-6 col-md-6">
                                            <label>Job Type</label>
                                            <select name="job_type" class="wt-search-bar-select selectpicker"  data-live-search="true" title="" id="j-All_Category" data-bv-field="size">
                                                <option  value="all" selected>All Categories</option>
                                                {% for item in job_types %}
                                                    <option value="{{ item }}">{{ item }}</option>
                                                {% endfor %} 
                                            </select>
                                        </div>

                                        <!--Location-->
                                        <div class="form-group col-xl-3 col-lg-6 col-md-6">
                                            <label>Location</label>
                                            <div class="twm-inputicon-box">
                                                <input name="location" type="text" required class="form-control" placeholder="Search..." required>
                                                <i class="twm-input-icon fas fa-map-marker-alt"></i>
                                            </div>
                                        </div>

                                        <!--Find job btn-->
                                        <div class="form-group col-xl-3 col-lg-6 col-md-6">
                                            <button type="submit" class="site-button" style="background-color:#24695c">Find Job</button>
                                        </div>

                                    </div>
                                </form>
                            </div>



                                

                            </div>

                            <div class="row">
                                <!--Block one-->
                                {% for item in jobs %}
                                <div class="col-lg-6 col-md-12 m-b30">

                                    <div class="twm-jobs-grid-style1">
                                        <div class="twm-media">
                                            <img src="{{ item.company_logo.url }}" alt="#">
                                        </div>
                                        
                                        <div class="twm-jobs-category green"><span class="twm-bg-green">{{ item.job_type }}</span></div>
                                        <div class="twm-mid-content">
                                            <a href="{% url 'job:job_detail' item.id %}" class="twm-job-title">
                                                <h4>{{ item.title }}</h4>
                                            </a>
                                            <p class="" style="color: #2db346">{{ item.pub_date }}</p>
                                            <p class="twm-job-address">{{ item.description|safe|truncatewords:10 }}</p>
                                            <a target="_blank" href="{{ item.website }}" class="twm-job-websites site-text-primary">{{ item.website }}</a>
                                        </div>
                                        <div class="twm-right-content">
                                            
                                            <div class="twm-jobs-amount">${{ item.salary }} <span>/ Year</span></div>
                                            <a href="{% url 'job:job_detail' item.id %}" class="twm-jobs-browse site-text-primary">Browse Job</a>
                                        </div>
                                    </div>

                                </div>
                                {% endfor %}
                                
                                
                                </div>
                            </div>

                             
                        <!--
                            <div class="pagination-outer">
                                <div class="pagination-style1">
                                    <ul class="clearfix">
                                        <li class="prev"><a href="javascript:;"><span> <i class="fa fa-angle-left"></i> </span></a></li>
                                        <li><a href="javascript:;">1</a></li>
                                        <li class="active"><a href="javascript:;">2</a></li>
                                        <li><a href="javascript:;">3</a></li>
                                        <li><a class="javascript:;" href="javascript:;"><i class="fa fa-ellipsis-h"></i></a></li>
                                        <li><a href="javascript:;">5</a></li>
                                        <li class="next"><a href="javascript:;"><span> <i class="fa fa-angle-right"></i> </span></a></li>
                                    </ul>
                                </div>
                            </div>
                        -->
                        </div>

                    </div>
                </div>
            </div>   
            <!-- OUR BLOG END -->
          
           <style>
                @media only screen and (max-width: 600px) {
                .query {
                    display: none;
                    }
                }
            </style> 
        </div>
        <!-- CONTENT END -->

{% endblock %}