aibraV2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    #path("", include("main.urls")),
    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("job/", include("job.urls")),
    path("resume/", include("resume.urls")),
    path("quiz/", include("quiz.urls")),

    path("stake/", include("stake.urls")),
    path("interview/", include("interview.urls")),
    path("admin-app/", include("admin_app.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("job-detail/<int:job_id>/", views.JobDetailView, name="job_detail"),
	path("apply-job/<int:job_id>/<int:app_user_id>/", views.ApplyJobView, name="apply_job"),
	path("my-applications/", views.MyApplicationsView, name="my_applications"),

	path("request-candiates/", views.RequestView, name="request"),
	path("manage-job/", views.ManageJobView, name="manage_job"),
	path("all-requests/", views.AllRequestsView, name="all_requests"),
	path("edit_request/<int:request_id>/", views.EditRequestView, name="edit_request"),
	path("request-detail/<int:request_id>/", views.RequestDetailView, name="request_detail"),
	path("assign/<int:request_id>/", views.AssignView, name="assign"),
	path("assign/<int:request_id>/<str:recruiter>/", views.Assign2View, name="assign2"),



	path("add-job/", views.AddJobView, name="add_job"),
	path("add-job-from-request/<int:request_id>/", views.AddJobFRView, name="add_job_fr"),

	path("job-applications/<int:job_id>/", views.JobApplicationsView, name="job_applications"),
	path("edit-job/<int:job_id>/", views.EditJobView, name="edit_job"),

	path("search-job/<str:query_type>/<str:query>/", views.SearchJobView, name="search_job"),
	path("all-location-jobs/<str:query>/", views.AllLocationView, name="all_location"),
	
]

stake/urls.py
from django.urls import path
from . import views

app_name = "staking"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("stake/", views.StakeView, name="stake"),
	path("stake/metamask/", views.StakeWithMView, name="stake_metamask"),
	path("stake/metamask/pay/", views.StakeWithM2View, name="stake_metamask2"),
	path("my-stakes/", views.MyStakesView, name="my_stakes"),

	path("make-payment/<int:staking_id>/", views.MakePaymentView, name="make_payment"),
	path("confirm-payment/<int:staking_id>/", views.ConfirmPaymentView, name="confirm_payment"),

	path("request-payment/<int:staking_id>/", views.RequestPaymentView, name="request_payment"),

]

stake/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from app_user.models import AppUser


class Stake(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	amount = models.FloatField(default=0)
	duration = models.IntegerField(default=0)
	returns = models.FloatField(default=0)
	
	amount_tax = models.FloatField(default=0)
	returns_tax = models.FloatField(default=0)
	total_tax = models.FloatField(default=0)
	
	payment_hash = models.CharField(default="none", max_length=50)
	payment_status = models.BooleanField(default=False)
	payment_confirmation_status = models.BooleanField(default=False)

	request_payment_status = models.BooleanField(default=False)
	closed_status = models.BooleanField(default=False)

	due_date = models.DateTimeField(default=timezone.now)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.app_user.user.username

		

stake/views.py
from django.contrib import messages
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                            get_object_or_404, redirect, render)
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from app_user.models import *
from stake.models import *
import requests

from django.utils import timezone
import datetime
from django.contrib.auth.decorators import login_required

from wallet.views import RayGetName

@login_required(login_url='/app/sign-up/')
def IndexView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)

    if app_user.user.username == app_user.wallet_address:
        return HttpResponseRedirect(reverse("staking:stake_metamask2"))
    else:
        return HttpResponseRedirect(reverse("staking:stake"))



@login_required(login_url='/app/sign-up/')
def StakeView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        amount = float(request.POST.get("amount"))
        app_user = AppUser.objects.get(user__pk=request.user.id)
        duration = request.POST.get("duration")

        bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()

        #return HttpResponse(str(float(bep_balance["data"][0]["balance"])))
        if float(float(bep_balance["data"][0]["balance"])) > amount:
            
            sender = app_user.wallet_address
            sender_key = app_user.wallet_key
            receiver = "0xbCA60DDe596B82a4Cb8CC3233BF8f0ED09280557"
            amount = amount
            token = "abr"
        
            try:
                resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key":sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
                txn_hash = resp["txn_hash"]
                
            except:
                txn_hash = None
                
            sender = app_user.wallet_address
            sender_key = app_user.wallet_key
            receiver = "0xbCA60DDe596B82a4Cb8CC3233BF8f0ED09280557"
            amount2 = float(amount*0.01)
            token = "abr"
        
            #try:
            #    resp2 = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key":sender_key, "receiver": receiver, "amount":amount2, "token":token}).json()
            #    txn_hash2 = resp2["txn_hash"]
                
            #except:
            #    txn_hash2 = None
                

            #return HttpResponse(str(txn_hash))
            if txn_hash != None:
                stake = Stake.objects.create(app_user=app_user, amount=amount, duration=duration)
                stake.save()

                #returns block
                if duration == "60":
                    returns = float(amount) + float(amount)*0.1 #25%
                    returnsk = float(float(returns)*0.03) + float(float(amount)*0.01)
                    returns = float(returns) - float(returnsk)
            
                else:
                    returns = float(amount) + float(amount)*0.1 #25%
                stake.returns = returns

                payment_hash = txn_hash
                stake.payment_hash = payment_hash
                stake.payment_status = True
                stake.amount_tax = float(float(amount)*0.01)
                stake.returns_tax = float(float(returns)*0.03)
                stake.total_tax = returnsk
                stake.payment_confirmation_status = True
                

                today = timezone.now().date()
                due_date = today + datetime.timedelta(days=int(duration))
                stake.due_date = due_date

                stake.save()

                messages.warning(request, "Congratulations! you have successfully staked your asset! %s" % (txn_hash))
                return HttpResponseRedirect(reverse("staking:my_stakes"))

            else:
                messages.warning(request, "Sorry!! your staking could not go through.(Try top-up your account.._")
                return HttpResponseRedirect(reverse("staking:stake"))

        else:
                messages.warning(request, "Sorry! something went wrong. (Try top-up your account.)")
                return HttpResponseRedirect(reverse("staking:stake"))


    else:
        #resp = requests.get("https://api.iotexchartapp.com/brise-get-balance/%s" % (app_user.wallet_address)).json()
        #data = resp["data"]
        bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()
        brise_balance = float(float(bep_balance["data"][0]["balance"]))
        context = {"domain_name": RayGetName(app_user.wallet_address), "app_user": app_user, "brise_balance":brise_balance}
        return render(request, "stake/staking.html", context)


@login_required(login_url='/app/sign-up/')
def StakeWithMView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        amount = float(request.POST.get("amount"))
        app_user = AppUser.objects.get(user__pk=request.user.id)
        duration = request.POST.get("duration")

        bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()

        #return HttpResponse(str(float(bep_balance["data"][0]["balance"])))
        if float(float(bep_balance["data"][0]["balance"])) > amount:
            
            sender = app_user.wallet_address
            txn_hash = None
            if txn_hash != None:
                stake = Stake.objects.create(app_user=app_user, amount=amount, duration=duration)
                stake.save()

                #returns block
                if duration == "60":
                    returns = float(amount) + float(amount)*0.1 #25%
                    returnsk = float(float(returns)*0.03) + float(float(amount)*0.01)
                    returns = float(returns) - float(returnsk)
            
                else:
                    returns = float(amount) + float(amount)*0.1 #25%
                stake.returns = returns

                payment_hash = txn_hash
                stake.payment_hash = payment_hash
                stake.payment_status = True
                stake.amount_tax = float(float(amount)*0.01)
                stake.returns_tax = float(float(returns)*0.03)
                stake.total_tax = returnsk
                stake.payment_confirmation_status = True
                

                today = timezone.now().date()
                due_date = today + datetime.timedelta(days=int(duration))
                stake.due_date = due_date

                stake.save()

                messages.warning(request, "Congratulations! you have successfully staked your asset! %s" % (txn_hash))
                return HttpResponseRedirect(reverse("staking:my_stakes"))

            else:
                messages.warning(request, "Sorry!! your staking could not go through.(Try top-up your account.._")
                return HttpResponseRedirect(reverse("staking:stake_metamask2"))

        else:
                messages.warning(request, "Sorry! something went wrong. (Try top-up your account.)")
                return HttpResponseRedirect(reverse("staking:stake_metamask2"))


    else:
        #resp = requests.get("https://api.iotexchartapp.com/brise-get-balance/%s" % (app_user.wallet_address)).json()
        #data = resp["data"]
        bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()
        brise_balance = float(float(bep_balance["data"][0]["balance"]))
        context = {"app_user": app_user, "brise_balance":brise_balance}
        return render(request, "stake/staking2.html", context)
    
@login_required(login_url='/app/sign-up/')
def StakeWithM2View(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        amount = float(request.POST.get("amount"))
        txn_hash = request.POST.get("txn_hash")
        duration = "60"

        if txn_hash != "none": #it worked
            
            stake = Stake.objects.create(app_user=app_user, amount=amount, duration=duration)
            stake.save()

            #returns block
            if duration == "60":
                returns = float(amount) + float(amount)*0.1 #25%
                returnsk = float(float(returns)*0.03) + float(float(amount)*0.01)
                returns = float(returns) - float(returnsk)
        
            else:
                returns = float(amount) + float(amount)*0.1 #25%
            stake.returns = returns

            payment_hash = txn_hash
            stake.payment_hash = payment_hash
            stake.payment_status = True
            stake.amount_tax = float(float(amount)*0.01)
            stake.returns_tax = float(float(returns)*0.03)
            stake.total_tax = returnsk
            stake.payment_confirmation_status = True
            

            today = timezone.now().date()
            due_date = today + datetime.timedelta(days=int(duration))
            stake.due_date = due_date

            stake.save()

            messages.warning(request, "Congratulations! you have successfully staked your asset! %s" % (txn_hash))
            return HttpResponseRedirect(reverse("staking:my_stakes"))

        else:
            messages.warning(request, "Sorry! The transaction did not go through.")
            return HttpResponseRedirect(reverse("staking:stake_metamask2"))



    else:
        #resp = requests.get("https://api.iotexchartapp.com/brise-get-balance/%s" % (app_user.wallet_address)).json()
        #data = resp["data"]

stake/templates/stake/Untitled-1.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<style type="text/css">
    .ls-inputicon-box img{
     position: absolute !important;
     margin-top: 15px !important;
     left: 0;
     top: 0 !important;
     width: 30px !important;
     height: 30px !important;
     z-index: 5;
     line-height: 40px !important;
     text-align: center !important;
     font-size: 16px;
     color: #24695c;
    } 
</style>

{% include "app_user/header.html" %}

{% include "app_user/sidebar.html" %}

            <div id="content">

            <div class="content-admin-main">
            <div class
            ="twm-sign-up">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content" style="max-width: 450px !important;">
                    
                        <form method="POST">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h2 class="modal-title" id="sign_up_popupLabel2">Stake Aibra</h2>
                                <p>Stake ABR to recieve ABR</p>
                                
                            </div>
                            <div class="modal-body">
                                <div class="twm-tabs-style-2">
                                    
                                    
                                    <div class="tab-content" id="">
                                        <!--Login Candidate Content-->  
                                        <div class="tab-pane fade show active" id="login-candidate">
                                            <div class="row">

                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                         <label>Balance: {{ brise_balance|floatformat:3|intcomma }} ABR</label>
                                                        <input min="100000" name="amount" type="text" required="" class="form-control" placeholder="e.g 1000000000">
                                                    </div>
                                                </div>
                                                <small>minimum stake: 100,000.00 ABR</small>
                                                
                                                
                                                
                                                
                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Stake Duration:  <a href="javascript:;">60days</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Exchange rate:  <a href="javascript:;">1 ABR = 1 ABR</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Staking Fee:  <a href="javascript:;">1%</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Return:  <a href="javascript:;">10%</a></label>
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <button type="submit" class="site-button">Proceed</button>
                                                    
                                                </div>

                                                
                                                
                                            </div>
                                        </div>
                                        
                                    
                                    </div>
                                </div> 
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        <!--Model Popup Section End-->

{% endblock %}

stake/templates/stake/mystakes.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% include "app_user/header.html" %}
{% include "app_user/sidebar.html" %}

            <div id="content">

            <div class="content-admin-main">

            


            
                

                <div class="container">
                    <div class="row">
                        
                        

                        <div class="col-lg-12 col-md-12">
                            <!--Filter Short By-->
                            <br><br><br><br><br>
                            <div class="row">
                                <!--Block one-->
                                {% if my_stakes %}
                    				{% for item in my_stakes %}
                                <div class="col-lg-4 col-md-12 m-b30">

                                    <div class="twm-jobs-grid-style1">
                                        <div class="twm-media">
                                            <img src="{% static 'assets/images/stake.png' %}" alt="#">
                                        </div>
                                        
                                        <div class="twm-jobs-category green"><span class="twm-bg-green">{{ item.duration }} days</span></div>
                                        <div class="twm-mid-content">
                                            <a href="" class="twm-job-title">
                                                <h5>Amount Staked : {{ item.amount|floatformat:3|intcomma }} ABR<br /><small>(1% Fee: {{ item.amount_tax|floatformat:4|intcomma }}abr )</small></h5>
                                            </a>
                                            <p>{{ item.pub_date }}</p>
                                            <hr>
                                            <p class="twm-job-address">Return: <span style="float: right;">{% if item.duration == 60 %}
                                        								{{ return_checker }}
                                      										{% else %}
                                        									None%
                                      									{% endif %}</span>
                                      		</p>
                                            <hr>

                                      		<p class="twm-job-address">Expected Return:  <span style="float: right;">{{ item.returns|floatformat:4|intcomma }} ABR </span><br> <small>
                                      			(3% Fee: {{ item.returns_tax|floatformat:4|intcomma }}abr )
                                      		</small>

                                      		</p> 
                                            <hr>
                                            <p class="twm-jobs-amount">Unstake Date: <span style="float: right;">{{ item.due_date }}</span></p>
                                            <hr>
                                        </div>
                                        <div class="twm-right-content">
                                            
                                            
                                           
                                            <a href="{% url 'staking:request_payment' item.id %}" class="twm-jobs-browse site-text-primary">Unstake</a>
                                            <a href="{% url 'staking:index' %}" class="twm-jobs-browse site-text-primary">Stake</a>
                                        </div>
                                    </div>

                                </div>
                                {% endfor %}
                    			{% else %}

                    			<div class="col-lg-4 col-md-12 m-b30">


                                    

                                </div>
                                
                                <!--Block two-->
                                <div class="col-lg-4 col-md-12 m-b30">


                                    <div class="twm-jobs-grid-style1">
                                        



                                        <div class="twm-mid-content">
                                            <a href="{% url 'staking:index' %}" class="twm-job-title">
                                                <h4>You're in the right Place</h4>
                                            </a>
                                            <p class="twm-job-address">Sorry, you do not have any stakes. Click button below to stake Aibra</p>
                                            
                                        </div>
                                        <div class="twm-right-content">
                                            
                                            <a href="{% url 'staking:index' %}" class=" ftr-nw-subcribe-btn twm-jobs-browse site-text-primary">Stake Now</a>
                                        </div>
                                    </div>

                                </div>
                                {% endif %}  
                                
                                
                                

                            </div>

                            

                        </div>

                    </div>
                </div>
            </div>   
            <!-- OUR BLOG END -->

        </div>
        <!-- CONTENT END -->

{% endblock %}

stake/templates/stake/staking.html
{% extends 'app_user/auth_base.html' %}
{% load static %}
{% load humanize %}


{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="notification is-toast alert alert-{{message.tags}} text-center" role="alert" style="background-color: red; color: #fff; border-radius: 6px; font-weight: 600; z-index: 1;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<style type="text/css">
    .ls-inputicon-box img{
     position: absolute !important;
     margin-top: 15px !important;
     left: 0;
     top: 0 !important;
     width: 30px !important;
     height: 30px !important;
     z-index: 5;
     line-height: 40px !important;
     text-align: center !important;
     font-size: 16px;
     color: #24695c;
    } 
</style>

{% include "app_user/header.html" %}

{% include "app_user/sidebar.html" %}

            <div id="content">

            <div class="content-admin-main">
            <div class
            ="twm-sign-up">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content" style="max-width: 450px !important;">
                    
                        <form method="POST">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h2 class="modal-title" id="sign_up_popupLabel2">Stake Aibra</h2>
                                <p>Stake ABR to recieve ABR</p>
                                
                            </div>
                            <div class="modal-body">
                                <div class="twm-tabs-style-2">
                                    
                                    
                                    <div class="tab-content" id="">
                                        <!--Login Candidate Content-->  
                                        <div class="tab-pane fade show active" id="login-candidate">
                                            <div class="row">

                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                         <label>Balance: {{ brise_balance|floatformat:3|intcomma }} ABR</label>
                                                        <input name="amount" type="text" required="" class="form-control" placeholder="e.g 1000000000">
                                                    </div>
                                                </div>
                                                <small>minimum stake: 100,000.00 ABR</small>

                                                

                                                

                                            
                                                
                                                
                                                
                                                
                                                <div class="col-lg-12">
                                                    <div class="form-group mb-3">
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3" name="duration" value="60">
                                                            <label class="form-check-label rem-forgot">Stake Duration:  <a href="javascript:;">60days</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Exchange rate:  <a href="javascript:;">1 ABR = 1 ABR</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Staking Fee:  <a href="javascript:;">1%</a></label>
                                                            
                                                        </div>
                                                        <div class=" form-check">
                                                            <input type="checkbox" checked class="form-check-input" id="Password3">
                                                            <label class="form-check-label rem-forgot">Return:  <a href="javascript:;">10%</a></label>
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <button type="submit" class="site-button">Stake</button>
                                                    
                                                </div>

                                                
                                                
                                            </div>
                                        </div>
                                        
                                    
                                    </div>
                                </div> 
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        <!--Model Popup Section End-->

{% endblock %}