aibraV2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    #path("", include("main.urls")),
    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("job/", include("job.urls")),
    path("resume/", include("resume.urls")),
    path("quiz/", include("quiz.urls")),

    path("stake/", include("stake.urls")),
    path("interview/", include("interview.urls")),
    path("admin-app/", include("admin_app.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app_user/urls.py
from django.urls import path
from . import views

app_name = "app_user"

urlpatterns = [


	path("sign-in/", views.SignInView, name="sign_in"),
	path("sign-up/", views.SignUpView, name="sign_up"),
	path("sign-up/with-metamask/", views.SignUpView2, name="sign_up2"),
	path("maintain/", views.MaintainView, name="maintain"),
	path("sign-up/complete/", views.CompleteSignUpView, name="complete_sign_up"),
	path("sign-out/", views.SignOutView, name="sign_out"),

	path("forgot-password/", views.ForgotPasswordView, name="forgot_password"),
	path("set-new-password/", views.SetNewPView, name="set_new_p"),

	path("", views.AppView, name="app"),
	path("app/update-profile/", views.UpdateAppuserView, name="update_appuser"),
	path("recruits/", views.AllRecruitView, name="all_recruits"),
	path("app-user-detail/<int:app_user_id>/", views.AppUserDetailView, name="app_user_detail"),

	path("temp/", views.TempView, name="temp"),
	path("change-password/", views.ChangePasswordView, name="change_password"),

]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("job-detail/<int:job_id>/", views.JobDetailView, name="job_detail"),
	path("apply-job/<int:job_id>/<int:app_user_id>/", views.ApplyJobView, name="apply_job"),
	path("my-applications/", views.MyApplicationsView, name="my_applications"),

	path("request-candiates/", views.RequestView, name="request"),
	path("manage-job/", views.ManageJobView, name="manage_job"),
	path("all-requests/", views.AllRequestsView, name="all_requests"),
	path("edit_request/<int:request_id>/", views.EditRequestView, name="edit_request"),
	path("request-detail/<int:request_id>/", views.RequestDetailView, name="request_detail"),
	path("assign/<int:request_id>/", views.AssignView, name="assign"),
	path("assign/<int:request_id>/<str:recruiter>/", views.Assign2View, name="assign2"),



	path("add-job/", views.AddJobView, name="add_job"),
	path("add-job-from-request/<int:request_id>/", views.AddJobFRView, name="add_job_fr"),

	path("job-applications/<int:job_id>/", views.JobApplicationsView, name="job_applications"),
	path("edit-job/<int:job_id>/", views.EditJobView, name="edit_job"),

	path("search-job/<str:query_type>/<str:query>/", views.SearchJobView, name="search_job"),
	path("all-location-jobs/<str:query>/", views.AllLocationView, name="all_location"),
	
]

resume/urls.py
from django.urls import path
from . import views

app_name = "resume"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("update/resume/1/", views.UpdateResume1View, name="update_resume1"),

	path("update/resume/2/", views.UpdateResume2View, name="update_resume2"),


	path("update/resume/3/", views.UpdateResume3View, name="update_resume3"),
	path("update/resume/3/add-career/", views.AddCareerView, name="add_career"),
	path("update/resume/3/add-education/", views.AddEducationView, name="add_education"),
	path("update/resume/3/add-skill/", views.AddSkillView, name="add_skill"),

	path("update/resume/4/", views.UpdateResume4View, name="update_resume4"),
	path("update/resume/4/add-project/", views.AddProjectView, name="add_project"),
	path("update/resume/4/add-hobby/", views.AddHobbyView, name="add_hobby"),

	path("update/resume/5/", views.UpdateResume5View, name="update_resume5"),
	path("update/resume/5/add-award/", views.AddAwardView, name="add_award"),
	path("update/resume/5/add-referee/", views.AddRefereeView, name="add_referee"),


	#edits
	path("update/resume/5/edit-referee/<int:referee_id>/", views.EditRefereeView, name="edit_referee"),
	path("update/resume/5/edit-award/<int:award_id>/", views.EditAwardView, name="edit_award"),

	path("update/resume/5/edit-hobby/<int:hobby_id>/", views.EditHobbyView, name="edit_hobby"),
	path("update/resume/4/edit-project/<int:project_id>/", views.EditProjectView, name="edit_project"),
	path("update/resume/3/edit-skill/<int:skill_id>/", views.EditSkillView, name="edit_skill"),

	path("update/resume/3/edit-education/<int:education_id>/", views.EditEducationView, name="edit_education"),
	path("update/resume/3/edit-career/<int:career_id>/", views.EditCareerView, name="edit_career"),

	path("update/resume/2/edit-work-experience/<int:work_experience_id>/", views.EditResume2View, name="edit_resume2"),

]

stake/urls.py
from django.urls import path
from . import views

app_name = "staking"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("stake/", views.StakeView, name="stake"),
	path("stake/metamask/", views.StakeWithMView, name="stake_metamask"),
	path("stake/metamask/pay/", views.StakeWithM2View, name="stake_metamask2"),
	path("my-stakes/", views.MyStakesView, name="my_stakes"),

	path("make-payment/<int:staking_id>/", views.MakePaymentView, name="make_payment"),
	path("confirm-payment/<int:staking_id>/", views.ConfirmPaymentView, name="confirm_payment"),

	path("request-payment/<int:staking_id>/", views.RequestPaymentView, name="request_payment"),

]

wallet/urls.py
from django.urls import path
from . import views

app_name = "wallet"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("okx-wallet/", views.OkxView, name="okx_wallet"),
	#path("update/profile/", views.UpdateProfileView, name="update_profile"),
	path("send/", views.SendView, name="send"),
	path("send-token/<str:token_address>/", views.SendTokenView, name="send_token"),
	path("send-okx-token/<str:token_address>/", views.SendOKxTokenView, name="send_okx_token"),
	#path("bns/", views.BriseNameView, name="bns"),
	#path("dapp/", views.DappView, name="dapp"),
	#path("nft/", views.NFTView, name="nft"),
	#path("launchpad/", views.LaunchpadView, name="launchpad"),
	#path("aggregator/", views.AggView, name="aggregator"),
	path("swap/", views.SwapView, name="swap"),
	path("stake/", views.StakeView, name="stake"),
	path("mystakes/", views.MyStakeView, name="mystakes"),
	path("unstake/", views.UnStakeView, name="unstakes"),

]

app_user/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "first_name", "last_name", "password1", "password2")

app_user/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.core.mail import send_mail
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from datetime import datetime
import datetime as dt
import requests

from .forms import UserForm
from .models import AppUser
from resume.models import Resume
from django.contrib.auth.decorators import login_required

import random
import string
from job.models import Job

def ray_randomiser(length=6):
    landd = string.ascii_letters + string.digits
    return ''.join((random.choice(landd) for i in range(length)))
    

def RaySendMail(request, subject, message, to_email, code=None):

    try:
        context = {"subject": subject, "message": message, "code": code}
        html_message = render_to_string('app_user/message.html', context)
        message = strip_tags(message)

        send_mail(
            subject,
            message,
            'admin@aibra.io',
            [to_email,],
            html_message=html_message,
            fail_silently=False,
        )

    except:
        pass




def ForgotPasswordView(request):
    
    if request.method == "POST":
        email = request.POST.get("username")
        
        app_users = AppUser.objects.filter(user__username=email)
        
        if len(app_users) > 0:
            app_user = app_users.last()
            app_user.otp_code = ray_randomiser()
            app_user.save()
            
            RaySendMail(request, subject="Password Reset.", message="Looks like you lost your password. Kindly use this OTP code; %s to retrieve your account." % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

        
            messages.warning(request, "Set new password.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:forgot_password"))
        
        
    else:
        
        context = {}
        return render(request, "app_user/forgot_password.html", context)
        
        



def SetNewPView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        otp = request.POST.get("otp")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        
        app_users = AppUser.objects.filter(otp_code=otp)
        
        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
            
        elif len(app_users) > 0:
            app_user = app_users.last()
            
            user = app_user.user
            user.set_password(str(password2))
            user.save()
        
            messages.warning(request, "New Password Created!")
            return HttpResponseRedirect(reverse("app_user:sign_in"))
            
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        
    else:
        context = {"app_user":app_user}
        return render(request, "app_user/set_new_p.html", context)
        
        
                

def SignInView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)

                app_user = AppUser.objects.get(user__pk=request.user.id)
                
                if app_user.ec_status == True:
                    
                    if app_user.user.username == "odiagaraymondrayray@gmail.com":
                
                        print("11111111111111111111111111111111")
                        messages.success(request, "Welcome Onboard")
                        return HttpResponseRedirect(reverse("admin_app:index"))
                    
                    else:
                        print("22222222222222222222222222222222")
                        messages.warning(request, "Welcome Onboard")
                        return HttpResponseRedirect(reverse("job:index"))
                
                
                else:
                    print("22222222222222222222222222222222")
                    messages.warning(request, "Sorry, validate your account")
                    return HttpResponseRedirect(reverse("app_user:sign_in"))
                
            else:
                print("22222222222222222222222222222222")
                messages.warning(request, "Sorry, Invalid Login Details")
                return HttpResponseRedirect(reverse("app_user:sign_in"))

        else:
            print("33333333333333333333333333333333333333")
            messages.warning(request, "Sorry, Invalid Login Details")
            return HttpResponseRedirect(reverse("app_user:sign_in"))

    else:
        context = {}
        return render(request, "app_user/sign_in.html", context )




def SignUpView(request):
    if request.method == "POST":

        form = UserForm(request.POST or None, request.FILES or None)
        email = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        account_type = request.POST.get("account_type")


        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:sign_up"))

            
        else:
            try:
                AppUser.objects.get(user__email=request.POST.get("username"))
                messages.warning(request, "Email Address already taken!")
                return HttpResponseRedirect(reverse("app_user:sign_up"))


            except:
                user = form.save()
                user.set_password(request.POST.get("password1"))
                user.save()

                app_user = AppUser.objects.create(user=user, account_type=account_type)
                app_user.otp_code = ray_randomiser()

                resume = Resume.objects.create()
                resume.save

                app_user.resume = resume
                
                app_user.save()

                user = app_user.user
                user.email = email
                
                user.save()
                
                RaySendMail(request, subject="Email Confirmation.", message="Thank you for signing up with Aibra, Your OTP code is %s" % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

                if user:
                    if user.is_active:
                        login(request, user)

                        app_user = AppUser.objects.get(user__pk=request.user.id)
                        messages.warning(request, "An OTP code has been sent to your email")
                        return HttpResponseRedirect(reverse("app_user:complete_sign_up"))

    else:
        form = UserForm()
        context = {"form": form}
        return render(request, "app_user/sign_up.html", context )



    return render(request, "app_user/sign_up.html", context )



def SignUpView2(request):
    if request.method == "POST":

        wallet_address = request.POST.get("wallet_address")

        if wallet_address == "none":
            messages.warning(request, "Sorry, connect to metamask first.")
            return HttpResponseRedirect(reverse("app_user:sign_up"))

            
        else:
            otp_code = ray_randomiser()

            try:
                user = User.objects.get(username=wallet_address)
                
            except:
                user = User.objects.create(username=wallet_address)
                user.set_password(otp_code)
                user.save()
                

            try:
                app_user = AppUser.objects.get(wallet_address=wallet_address)
                
            except:
                app_user = AppUser.objects.create(user=user, wallet_address=wallet_address, account_type="candidate")
                app_user.otp_code = otp_code
                app_user.ec_status = True
                app_user.status = True

                resume = Resume.objects.create()
                resume.save

                app_user.resume = resume

            app_user.save()

            user = app_user.user
            user.email = wallet_address
            
            user.save()

            if user:
                if user.is_active:
                    login(request, user)

            messages.warning(request, "Welcome onboard.")
            return HttpResponseRedirect(reverse("job:index"))


    else:
        form = UserForm()
        context = {"form": form}
        return render(request, "app_user/sign_up2.html", context )

        
def CompleteSignUpView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        otp = request.POST.get("otp")
        
        
        if otp == app_user.otp_code:
            app_user.ec_status = True
            app_user.save()

            messages.warning(request, "Welcome Onboard!")
            return HttpResponseRedirect(reverse("app_user:update_appuser"))

        else:
            messages.warning(request, "Sorry, Invalid OTP Code.")

app_user/templates/app_user/message.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="../assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="../assets/images/favicon.png" type="image/x-icon">
    <title>viho - Premium Admin Template</title>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <style>
      body{
      width: 650px;
      font-family: work-Sans, sans-serif;
      background-color: #f6f7fb;
      display: block;
      }
      a{
      text-decoration: none;
      }
      span {
      font-size: 14px;
      }
      p {
          font-size: 13px;
         line-height: 1.7;
         letter-spacing: 0.7px;
         margin-top: 0;
      }
      .text-center{
      text-align: center
      }
    </style>
  </head>
  <body style="margin: 30px auto;">
    <table style="width: 100%">
      <tbody>
        <tr>
          <td>
            <table style="background-color: #f6f7fb; width: 100%">
              <tbody>
                <tr>
                  <td>
                    <table style="width: 650px; margin: 0 auto; margin-bottom: 30px">
                      <tbody>
                        <tr>
                          <td><img width="100px" src="https://aibra.io/static/main/images/aibra4.png" alt=""></td>
                          <td style="text-align: right; color:#999"><span>Some Description</span></td>
                        </tr>
                      </tbody>
                    </table>
                    <table style="width: 650px; margin: 0 auto; background-color: #fff; border-radius: 8px">
                      <tbody>
                        <tr>
                          <td style="padding: 30px"> 
                            <p>Hi There,</p>
                            <p>{{ message }}.....</p>
                           
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    
                    <table style="width: 650px; margin: 0 auto; background-color: #fff; border-radius: 8px">
                      <tbody>
                        <tr>
                          <td style="padding: 30px"> 
                            
                           <a {% if subject == "Aibra Jobs: New Job Alert!" %} href="https://app.aibra.io{% url 'job:job_detail' code %}" {% elif subject == "Aibra Jobs: New Application!" %} href="https://app.aibra.io{% url 'job:job_detail' code %}" {% else %} href="#" {% endif %}>
                                {% if subject == "Aibra Jobs: New Job Alert!" %}
                                        Apply!
                                        
                                {% elif subject == "Aibra Jobs: New Application!" %}
                                        View Applications
                            </a>
                                      {% else %}
                                        <a href="javascript:void(0)" style="padding: 10px; background-color: #24695c; color: #ffffff; display: inline-block; border-radius: 4px; margin-bottom: 18px">{{ code }} </a>
                                      {% endif %}
                            
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    
                    <table style="width: 650px; margin: 0 auto; margin-top: 30px">
                      <tbody>       
                        <tr style="text-align: center">
                          <td> 
                            <p style="color: #999; margin-bottom: 0">Get in touch <a href="mailto:info@aibra.io" style="color: #24695c">Info@aibra.io</a></p>
                            <p style="color: #999; margin-bottom: 0">Don't Like These Emails?<a href="javascript:void(0)" style="color: #24695c">Unsubscribe</a></p>
                            <p style="color: #999; margin-bottom: 0">Powered By AIbra Admin</p>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

app_user/templates/app_user/sidebar.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
<!-- Sidebar Holder -->
        <nav id="sidebar-admin-wraper" style="background-color:#cedfde">
            <div class="page-logo">
                <a href="/"><img src="https://aibra.io/static/main/images/aibra4.png" alt=""></a>
            </div>
            
            <div class="admin-nav scrollbar-macosx">
                <ul>
                    <li>
                        <a href="{% url 'app_user:app' %}"><i class="fa fa-home"></i><span class="admin-nav-text">Dashboard</span></a>
                    </li>
                    
                    {% url 'job:index' as index %}
                    <li class="{% if index == request.path %} active {% endif %}">
                        {% if app_user.account_type == "recruiter" %}
                        <a href="javascript:;"><i class="fa fa-suitcase"></i><span class="admin-nav-text">Jobs</span></a>
                        <ul class="sub-menu">
                            <li> <a href="{% url 'job:all_requests' %}"><span class="admin-nav-text">View Requests</span></a></li>
                            <li> <a href="{% url 'job:add_job' %}"><span class="admin-nav-text">Post a New Jobs</span></a></li>
                            <li> <a href="{% url 'job:manage_job' %}"><span class="admin-nav-text">Manage Jobs</span></a></li>
                            <li> <a href="{% url 'app_user:all_recruits' %}"><span class="admin-nav-text">All Candidates</span></a></li>
                        </ul>
                        {% endif %}
                        {% if app_user.account_type == "candidate" %}
                        <a href="javascript:;"><i class="fa fa-suitcase"></i><span class="admin-nav-text">Jobs</span></a>
                        <ul class="sub-menu">
                        <li> <a href="{% url 'job:index' %}"><span class="admin-nav-text">Available Jobs</span></a></li>
                        <li> <a href="{% url 'job:my_applications' %}"><span class="admin-nav-text">My Applications</span></a></li>
                        </ul>

                        {% endif %}
                        {% if app_user.account_type == "company" %}
                        <li><a href="{% url 'job:request' %}"><span class="admin-nav-text">Request Candidate</span></a></li>
                        {% endif %} 
                    {% url 'resume:index' as resume %}
                    <li class="{% if resume == request.path %} active {% endif %}">
                        <a href="{{ resume }}"><i class="fa fa-receipt"></i><span class="admin-nav-text">Resume</span></a>
                    </li>
                    
                    
                    <li class="">
                        <a href="javascript:;"><i class="fa fa-money-bill-alt"></i><span class="admin-nav-text">Wallet</span></a>
                        <ul class="sub-menu">
                            <li> <a href="{% url 'wallet:index' %}"><span class="admin-nav-text">Bitgert Wallet</span></a></li>
                             <li> <a href="{% url 'wallet:okx_wallet' %}"><span class="admin-nav-text">OKx Chain Wallet</span></a></li>
                           
                        </ul>
                    </li>
                     {% url 'staking:my_stakes' as my_stakes %} 
                    <li class="{% if my_stake == request.path %} active {% endif %}">
                        <a href="javascript:;"><i class="fas fa-money-bill-wave"></i><span class="admin-nav-text">Earnings <sup class="twm-msg-noti">2</sup></span></a>
                        <ul class="sub-menu">
                            
                            <li> <a href="{{ my_stakes }}"><span class="admin-nav-text">Staking</span></a></li>

                            <li> <a href="#"><span class="admin-nav-text">Referral(Coming Soon)</span></a></li>
                        </ul>
                    </li>

                      
                    <!--
                    <li>
                        <a href=""><i class="fa fa-comments"></i><span class="admin-nav-text">Chat</span></a>
                    </li>
                    -->
                    <li>
                        <a href=""><i class="fa fa-fingerprint"></i><span class="admin-nav-text">Change Password</span></a>
                    </li>
                    <!--
                    <li>
                        <a href="javascript:;"><i class="fa fa-book-reader"></i><span class="admin-nav-text">Learning</span></a>
                    </li>
                    -->
                    <li>
                        <a href="https://blog.aibra.io" target="_blank"><i class="fa fa-blog"></i><span class="admin-nav-text">Blog</span></a>
                    </li>  
                                       
                    <li>
                        <a href="javascript:;" data-bs-toggle="modal" data-bs-target="#logout-dash-profile"><i class="fa fa-share-square"></i><span class="admin-nav-text">Logout</span></a>
                    </li>                    
                    
                </ul>
            </div>   
        </nav>

        <!--Logout Profile Popup-->
        <div class="modal fade twm-model-popup" id="logout-dash-profile" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h4 class="modal-title">Do you want to Logout your profile?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="site-button" data-bs-dismiss="modal">No</button>
                    <a role="button" href="{% url 'app_user:sign_out' %}" type="button" class="site-button outline-primary">Yes</a>
                </div>
            </div>
            </div>
        </div>

        <!-- Page Content Holder -->